export const allAuctions: Auction[] = [
  {
    id: 1,
    title: "Vintage Phone",
    description: "A classic rotary dial telephone from the 1960s.",
    currentBid: 550,
    startingBid: 500,
    bidInterval: 25,
    timeLeft: "2 hours",
    image: "/images/placeholder.avif",
  },
  {
    id: 2,
    title: "Antique Clock",
    description: "Beautifully crafted grandfather clock from the 18th century.",
    currentBid: 300,
    startingBid: 250,
    bidInterval: 20,
    timeLeft: "1 day",
    image: "/images/placeholder.avif",
  },
  {
    id: 3,
    title: "Rare Coin",
    description: "A well-preserved ancient Roman gold coin.",
    currentBid: 1000,
    startingBid: 800,
    bidInterval: 50,
    timeLeft: "3 hours",
    image: "/images/placeholder.avif",
  },
  {
    id: 4,
    title: "Classic Car",
    description: "Fully restored 1957 Chevrolet Bel Air in mint condition.",
    currentBid: 15000,
    startingBid: 12000,
    bidInterval: 500,
    timeLeft: "5 days",
    image: "/images/placeholder.avif",
  },
];

export const myAuctions: Auction[] = [
  {
    id: 2,
    title: "Antique Clock",
    description: "Beautifully crafted grandfather clock from the 18th century.",
    currentBid: 300,
    startingBid: 250,
    bidInterval: 20,
    timeLeft: "1 day",
    image: "/images/placeholder.avif",
  },
  {
    id: 4,
    title: "Classic Car",
    description: "Fully restored 1957 Chevrolet Bel Air in mint condition.",
    currentBid: 15000,
    startingBid: 12000,
    bidInterval: 500,
    timeLeft: "5 days",
    image: "/images/placeholder.avif",
  },
];
